# Basic Information 
title: Wen Zhong
position: Postdoc
affiliation: Virginia Tech
email: wenzhong24@vt.edu

# Search Engine Optimization (SEO)
keywords: wen zhong, zhong wen
canonical: https://wenzhong23.github.io/
description: Wen Zhong works as a Postdoc at Virginia Tech. Her research focuses on land subsidence investigation and flooding analysis.

# The option is used to show the last update time.
enable_last_update: true

# Links
google_scholar: https://scholar.google.com/citations?user=Xj3uOfUAAAAJ&hl=en
researchgate: https://www.researchgate.net/profile/Wen-Zhong-3
twitter: https://twitter.com/Wen_Zhong_
cv_link: https://drive.google.com/file/d/1_kWjcUHizGGheXU5_wYcaHc0IKuhtiqT/view?usp=sharing
github_link: https://github.com/wenzhong23
linkedin: https://www.linkedin.com/in/wen-zhong-9a59771a5/


# Images 
avatar: ./assets/img/personal img.jpg
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: wzhong@islander.tamucc.edu

remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
